version: '3.7'
services:
  mosquitto_broker:
    image: mosquitto_service
    restart: always
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
      - 1883:1883 
    expose:
      - "1883"
  py_publisher:
    image: publisher_service
    restart: always
    build:
      context: ./publisher
      dockerfile: Dockerfile
    ports:
      - 9050:9050
    depends_on:
      - mosquitto_broker
  database_mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbadmin
      - MONGO_INITDB_ROOT_PASSWORD=a3Ngrc0Y9RPQYTr
      - MONGO_INITDB_DATABASE:sensordb
    volumes:
      - type: bind
        source: ./mongodb/data
        target: /mongodb/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  cache_redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=J9oM3w1bCr9710A
      - REDIS_DB=0
      - REDIS_REPLICATION_MODE=master
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "J9oM3w1bCr9710A"
    ports:
      - 6379:6379/tcp
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  py_subscriber:
    image: subscriber_service
    restart: always
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    depends_on:
       - mosquitto_broker
       - cache_redis
       - database_mongo
       - py_publisher
  py_webapp:
    image: webapp_api_service
    restart: always
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 9070:9070
    depends_on:
       - mosquitto_broker
       - py_publisher
       - py_subscriber
       - cache_redis
       - database_mongo