version: '3.7'
services:
  mosquitto_broker:
    image: mosquitto_service
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
      - 1883:1883 
    expose:
      - "1883"
    

# networks:
#   mosquitto: